[package]
name = "hero-core"
authors = ["katsumi143 <32640219+katsumi143@users.noreply.github.com>"]
version = "0.0.1"
description = "an application that eases management of video games"

readme = "../../README.md"
license = "AGPL-3.0-only"
homepage = "https://hero-devs.com"
repository = "https://github.com/hero-devs/HERO"

edition = "2021"
rust-version = "1.73"

[dependencies]
dirs = { version = "5.0.1", optional = true }
uuid = { version = "1.5.0", features = ["v4", "serde"] }
egui = { version = "0.23.0", optional = true, default-features = false }
serde = { version = "1.0.190", features = ["derive"] }
libloading = { version = "0.8.1", optional = true }
serde_json = { version = "1.0.107", optional = true }
parking_lot = { version = "0.12.1", features = ["send_guard"] }

[features]
ui = []
core = ["dep:dirs", "dep:libloading", "dep:serde_json"]
egui = ["dep:egui"]